---
title: "Read VOC Canister Data"
output:
  html_document:
    toc: true
    toc_float: true
    theme: paper
---

```{r [ackages, include = FALSE]}

library(tidyverse)
library(plyr)
library(faraway)
library(cowplot)
library(reshape2)
library(corrplot)
library(scales)
library(ggthemes)
library(gridExtra)
library(patchwork)
library(gghighlight)
library(ggdark)
library(viridis)
library(DT)
library(plotly)
library(knitr)
library(magick)

```


```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.path = 'figures/',
  warning = FALSE,
  message = FALSE,
  echo = FALSE,
  fig.width = 6, fig.height = 3,
  cache = FALSE)
```

```{r}
library(googlesheets4)
```

```{r}
fldr <- if_else(.Platform$OS.type == "unix",
                "/Volumes/iaqv/",
                "T:/Projects/iaqv/")
```

```{r}
files_voc <- list.files(paste0(fldr, "data/canister/"), pattern = ".csv$", full.names = TRUE, recursive = "TRUE")
```

```{r}
read_site_data <- function(id_sheet, id_tab){
  read_sheet(id_sheet, id_tab, col_types = "c")
}
```


```{r}
logs_voc <- tibble(id_site = c("040", "063", "066", "079", "085", "086", "094",
                               "099", "103", "107", "108"),
                   id_sheet = c("1o8YkndN5TkwzOk2--dVmP3frEHOakLdMUrrvDB0W-DE",
                                "1epWhdCVkhUVVLSsC1bfP17OrGgRlqyIrh5WWcwFIYtM",
                                "1_MS6QAfXZlGRBiCGubXKgNI9vEtR1tTcw6gPfw9NObA",
                                "1qIx_hinRb__owvlhFxZBN9sUSdfoUNhSb6Q0Vz2KIhY",
                                "1i-PHsSD_DoRlOp44OVMlvZZayq9EMb1dMWLD--p9pwo",
                                "1ldSA5KtDp1pUBNVF2KUr2QMYzwccv1GVPo1idH9IfqI",
                                "1NHUvy3h-o8_6rbAKDNo94OCl5Lq6BfqDCM8Wo0F_ZLg",
                                "1fvWuuiV8C17nAEqZzn4wgq4NkhM9_LXyM4aL-ta8drc",
                                "1wEjC91BMCNuYcRpY1RuDEh1UNknz2OjwW0glTt2v5ig",
                                "1oWQ4KLEu234oncUy8CX0M_W3pMTVu5s5kTFWHRoGMJ0",
                                "1u41ObkKF5BgxhzRrpa9grezP1ZVokvVDlzmSKrMA2ZM")) %>%
  mutate(meta = map(id_sheet, read_site_data, "canister")) %>%
  unnest_longer("meta", keep_empty = TRUE) %>% unnest(meta) %>%
  mutate(id_canister = str_sub(id_canister, str_length(id_canister) - 1,
                                            str_length(id_canister)))
```

```{r}
read_canister <- function(file){
  read_csv(file, col_types = "c") %>%
  slice(2:n()) %>%
  rename_all(tolower) %>%
  mutate(id_site =  str_split(file, "/")[[1]][6]) %>%
  rename("id_canister" = "canister designation") %>%
  select(id_site, id_canister, 7:ncol(.)) %>%
  pivot_longer(-c("id_site", "id_canister"), names_to = "var", values_to = "val") %>%
  mutate(val = as.numeric(val),
         id_canister = str_sub(id_canister, str_length(id_canister) - 1,
                                            str_length(id_canister)))
}
```

```{r}
data_voc <- map(files_voc, read_canister) %>%
  bind_rows() %>%
  right_join(logs_voc, by = c("id_site", "id_canister"))
```

```{r}
tvoc <- data_voc %>% 
  group_by(id_site, building, id_room, id_canister) %>% 
  summarise(tvoc = sum(val,na.rm = TRUE), .groups = "drop")
```


```{r site_040 plot}
#need to change id_room to room names for plots
site_040 <- tvoc %>% 
  filter(id_site == "040")

ggplot(site_040, aes(x = id_room, y = tvoc)) +
  geom_bar(stat = "identity", fill = "midnightblue") +
  stat_summary(aes(label = stat(y)), fun = "sum", geom = "text",
               col = "white", vjust = 1.5) +
  ggtitle("Site 040") +
  labs(x = "", y = "")+
  theme_bw() +
  theme(axis.text.x = element_text(size = 10), axis.text.y = element_blank())

```

---